packages:
  - 'apps/*'
  - 'packages/*'
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - turbo
  - sharp
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  turbo: true
  sharp: true
